import { useState, useEffect } from 'react';
import { 
  DollarSign, 
  Car, 
  Clock, 
  ClipboardCheck,
  Send,
  Calculator,
  ChevronDown,
  ChevronUp
} from 'lucide-react';
import { Button } from '../../components/ui/Button';
import { Card } from '../../components/ui/Card';
import { Input } from '../../components/ui/Input';

// Pay rates
const MILEAGE_RATE = 0.55; // per mile
const WALKTHROUGH_RATE = 400; // flat
const HOURLY_RATE = 40; // per hour for return work

interface PayEntry {
  id: string;
  date: string;
  type: 'walkthrough' | 'return' | 'windshield';
  milesOneWay: number;
  hours?: number;
  customerName?: string;
  address?: string;
  notes?: string;
}

export function PayCalculator() {
  const [entries, setEntries] = useState<PayEntry[]>([]);
  const [showAddForm, setShowAddForm] = useState(true);
  
  // Form state
  const [entryType, setEntryType] = useState<'walkthrough' | 'return' | 'windshield'>('walkthrough');
  const [milesOneWay, setMilesOneWay] = useState('');
  const [hours, setHours] = useState('');
  const [customerName, setCustomerName] = useState('');
  const [address, setAddress] = useState('');
  const [notes, setNotes] = useState('');
  const [date, setDate] = useState(new Date().toISOString().split('T')[0]);

  // Load entries from localStorage
  useEffect(() => {
    const saved = localStorage.getItem('payEntries');
    if (saved) {
      setEntries(JSON.parse(saved));
    }
  }, []);

  // Save entries to localStorage
  useEffect(() => {
    localStorage.setItem('payEntries', JSON.stringify(entries));
  }, [entries]);

  const calculateEntry = (entry: PayEntry) => {
    const mileageTotal = entry.milesOneWay * 2 * MILEAGE_RATE;
    let serviceTotal = 0;
    
    if (entry.type === 'walkthrough') {
      serviceTotal = WALKTHROUGH_RATE;
    } else if (entry.type === 'return' || entry.type === 'windshield') {
      serviceTotal = (entry.hours || 0) * HOURLY_RATE;
    }
    
    return {
      mileage: mileageTotal,
      service: serviceTotal,
      total: mileageTotal + serviceTotal,
    };
  };

  const addEntry = () => {
    if (!milesOneWay) return;
    
    const newEntry: PayEntry = {
      id: Date.now().toString(),
      date,
      type: entryType,
      milesOneWay: parseFloat(milesOneWay) || 0,
      hours: entryType !== 'walkthrough' ? parseFloat(hours) || 0 : undefined,
      customerName,
      address,
      notes,
    };
    
    setEntries(prev => [newEntry, ...prev]);
    
    // Reset form
    setMilesOneWay('');
    setHours('');
    setCustomerName('');
    setAddress('');
    setNotes('');
    setShowAddForm(false);
  };

  const removeEntry = (id: string) => {
    setEntries(prev => prev.filter(e => e.id !== id));
  };

  const totals = entries.reduce(
    (acc, entry) => {
      const calc = calculateEntry(entry);
      return {
        mileage: acc.mileage + calc.mileage,
        service: acc.service + calc.service,
        total: acc.total + calc.total,
        miles: acc.miles + (entry.milesOneWay * 2),
        walkthroughs: acc.walkthroughs + (entry.type === 'walkthrough' ? 1 : 0),
        returnHours: acc.returnHours + (entry.type === 'return' ? (entry.hours || 0) : 0),
      };
    },
    { mileage: 0, service: 0, total: 0, miles: 0, walkthroughs: 0, returnHours: 0 }
  );

  const emailPaySheet = () => {
    const subject = `Pay Sheet - ${new Date().toLocaleDateString()}`;
    const body = `Pay Sheet Summary
================

Date Range: ${entries.length > 0 ? entries[entries.length - 1].date : ''} to ${entries.length > 0 ? entries[0].date : ''}

TOTALS:
- Walk-throughs: ${totals.walkthroughs} × $${WALKTHROUGH_RATE} = $${(totals.walkthroughs * WALKTHROUGH_RATE).toFixed(2)}
- Return Hours: ${totals.returnHours.toFixed(1)} hrs × $${HOURLY_RATE}/hr = $${(totals.returnHours * HOURLY_RATE).toFixed(2)}
- Mileage: ${totals.miles.toFixed(1)} mi × $${MILEAGE_RATE}/mi = $${totals.mileage.toFixed(2)}

GRAND TOTAL: $${totals.total.toFixed(2)}

DETAILS:
${entries.map(e => {
  const calc = calculateEntry(e);
  return `${e.date} | ${e.type.toUpperCase()} | ${e.customerName || 'N/A'} | ${e.milesOneWay * 2} mi | $${calc.total.toFixed(2)}`;
}).join('\n')}

--
Generated by FieldSync`;

    const recipients = 'Matt@nobilityhomes.com,Sharon@nobilityhomes.com,Diane@nobilityhomes.com';
    window.location.href = `mailto:${recipients}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
  };

  return (
    <div className="min-h-screen bg-gray-50 pb-24">
      {/* Header */}
      <div className="bg-white border-b px-4 py-4">
        <h1 className="text-2xl font-bold text-gray-900">Pay Calculator</h1>
        <p className="text-sm text-gray-500 mt-1">Track mileage, walk-throughs, and return work</p>
      </div>

      {/* Summary Card */}
      <div className="p-4">
        <Card className="bg-gradient-to-br from-green-500 to-green-600 text-white">
          <div className="text-center">
            <p className="text-green-100 text-sm">Total Earnings</p>
            <p className="text-4xl font-bold mt-1">${totals.total.toFixed(2)}</p>
          </div>
          <div className="grid grid-cols-3 gap-4 mt-4 pt-4 border-t border-green-400">
            <div className="text-center">
              <p className="text-green-100 text-xs">Walk-throughs</p>
              <p className="font-semibold">{totals.walkthroughs}</p>
            </div>
            <div className="text-center">
              <p className="text-green-100 text-xs">Return Hrs</p>
              <p className="font-semibold">{totals.returnHours.toFixed(1)}</p>
            </div>
            <div className="text-center">
              <p className="text-green-100 text-xs">Miles</p>
              <p className="font-semibold">{totals.miles.toFixed(0)}</p>
            </div>
          </div>
        </Card>
      </div>

      {/* Add Entry Form */}
      <div className="px-4">
        <button
          onClick={() => setShowAddForm(!showAddForm)}
          className="w-full flex items-center justify-between p-4 bg-white rounded-lg border mb-4"
        >
          <span className="font-medium text-gray-900">Add Entry</span>
          {showAddForm ? <ChevronUp className="w-5 h-5" /> : <ChevronDown className="w-5 h-5" />}
        </button>

        {showAddForm && (
          <Card className="mb-4">
            {/* Entry Type */}
            <div className="grid grid-cols-3 gap-2 mb-4">
              {[
                { type: 'walkthrough' as const, label: 'Walk-through', icon: ClipboardCheck },
                { type: 'return' as const, label: 'Return Work', icon: Clock },
                { type: 'windshield' as const, label: 'Windshield', icon: Car },
              ].map(({ type, label, icon: Icon }) => (
                <button
                  key={type}
                  onClick={() => setEntryType(type)}
                  className={`p-3 rounded-lg border-2 transition-colors ${
                    entryType === type
                      ? 'border-primary-500 bg-primary-50 text-primary-700'
                      : 'border-gray-200 text-gray-600'
                  }`}
                >
                  <Icon className="w-5 h-5 mx-auto mb-1" />
                  <span className="text-xs font-medium">{label}</span>
                </button>
              ))}
            </div>

            <div className="space-y-3">
              <Input
                label="Date"
                type="date"
                value={date}
                onChange={(e) => setDate(e.target.value)}
              />

              <Input
                label="Miles (one way)"
                type="number"
                placeholder="e.g., 45"
                value={milesOneWay}
                onChange={(e) => setMilesOneWay(e.target.value)}
              />

              {entryType !== 'walkthrough' && (
                <Input
                  label="Hours worked"
                  type="number"
                  step="0.5"
                  placeholder="e.g., 2.5"
                  value={hours}
                  onChange={(e) => setHours(e.target.value)}
                />
              )}

              <Input
                label="Customer name (optional)"
                placeholder="John Smith"
                value={customerName}
                onChange={(e) => setCustomerName(e.target.value)}
              />

              <Input
                label="Address (optional)"
                placeholder="123 Main St, Ocala"
                value={address}
                onChange={(e) => setAddress(e.target.value)}
              />

              {/* Live calculation */}
              {milesOneWay && (
                <div className="bg-gray-50 rounded-lg p-3 text-sm">
                  <div className="flex justify-between">
                    <span>Mileage ({milesOneWay} × 2 × ${MILEAGE_RATE})</span>
                    <span className="font-medium">${(parseFloat(milesOneWay) * 2 * MILEAGE_RATE).toFixed(2)}</span>
                  </div>
                  {entryType === 'walkthrough' && (
                    <div className="flex justify-between mt-1">
                      <span>Walk-through flat rate</span>
                      <span className="font-medium">${WALKTHROUGH_RATE.toFixed(2)}</span>
                    </div>
                  )}
                  {entryType !== 'walkthrough' && hours && (
                    <div className="flex justify-between mt-1">
                      <span>Hourly ({hours} × ${HOURLY_RATE})</span>
                      <span className="font-medium">${(parseFloat(hours) * HOURLY_RATE).toFixed(2)}</span>
                    </div>
                  )}
                  <div className="flex justify-between mt-2 pt-2 border-t font-semibold">
                    <span>Entry Total</span>
                    <span className="text-green-600">
                      ${(
                        (parseFloat(milesOneWay) || 0) * 2 * MILEAGE_RATE +
                        (entryType === 'walkthrough' ? WALKTHROUGH_RATE : (parseFloat(hours) || 0) * HOURLY_RATE)
                      ).toFixed(2)}
                    </span>
                  </div>
                </div>
              )}

              <Button onClick={addEntry} fullWidth disabled={!milesOneWay}>
                <Calculator className="w-4 h-4 mr-2" />
                Add Entry
              </Button>
            </div>
          </Card>
        )}
      </div>

      {/* Entries List */}
      <div className="px-4 space-y-2">
        {entries.map((entry) => {
          const calc = calculateEntry(entry);
          return (
            <Card key={entry.id} className="relative">
              <button
                onClick={() => removeEntry(entry.id)}
                className="absolute top-2 right-2 text-gray-400 hover:text-red-500 text-xs"
              >
                ✕
              </button>
              <div className="flex justify-between items-start">
                <div>
                  <p className="text-xs text-gray-500">{entry.date}</p>
                  <p className="font-medium text-gray-900 capitalize">{entry.type.replace('_', ' ')}</p>
                  {entry.customerName && (
                    <p className="text-sm text-gray-600">{entry.customerName}</p>
                  )}
                </div>
                <div className="text-right">
                  <p className="font-bold text-green-600">${calc.total.toFixed(2)}</p>
                  <p className="text-xs text-gray-500">{entry.milesOneWay * 2} mi</p>
                </div>
              </div>
            </Card>
          );
        })}

        {entries.length === 0 && (
          <div className="text-center py-8 text-gray-500">
            <Calculator className="w-12 h-12 mx-auto mb-2 text-gray-300" />
            <p>No entries yet</p>
            <p className="text-sm">Add your first work entry above</p>
          </div>
        )}
      </div>

      {/* Email Button */}
      {entries.length > 0 && (
        <div className="fixed bottom-20 left-0 right-0 p-4 bg-white border-t">
          <Button onClick={emailPaySheet} fullWidth>
            <Send className="w-4 h-4 mr-2" />
            Email Pay Sheet to Matt, Sharon & Diane
          </Button>
        </div>
      )}
    </div>
  );
}
